name: Test code

on:
  workflow_dispatch:

jobs:
  check:
    name: "Test static code"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      #with:
        #python-version: '3.11'

    #- name: Install Python dependencies
      #uses: py-actions/py-dependency-install@v4
      #with:
        #path: "${{ github.workspace }}/requirements.txt"
        #update-pip: "false"
        #update-setuptools: "false"
        #update-wheel: "false"

    - name: Install libraries
      run: pip install pandas

    - name: Install Pylint
      run: pip install pylint

    - name: Run Pylint
      run: |
         pylint $(git ls-files '*.py')
